version: "3.9"
services:
  order-service:
    build:
      context: .
      dockerfile: OrderService/dockerfile
    image: order-service:latest
    ports:
      - "80:80"
  
  inventory-service:
    build:
      context: .
      dockerfile: InventoryService/dockerfile
    image: inventory-service:latest
    ports:
      - "82:80"

  # gateway-service:
  #   build:
  #     context: ./GatewayService
  #     dockerfile: dockerfile
  #   image: gateway-service:latest
  #   ports:
  #     - "30080:80"  