version: "3.9"
services:
  order-service:
    build:
      context: ./OrderService
      dockerfile: dockerfile
    image: order-service:latest
    ports:
      - "80:80"
  
  shipping-service:
    build:
      context: ./ShippingService
      dockerfile: dockerfile
    image: shipping-service:latest
    ports:
      - "81:80"
  
  inventory-service:
    build:
      context: ./InventoryService
      dockerfile: dockerfile
    image: inventory-service:latest
    ports:
      - "82:80"
  
  payment-service:
    build:
      context: ./PaymentService
      dockerfile: dockerfile
    image: payment-service:latest
    ports:
      - "83:80"