apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway-service
  template:
    metadata:
      labels:
        app: gateway-service
    spec:
      serviceAccountName: saga-gateway-sa
      containers:
      - name: gateway-service
        image: gateway-service:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        # env:
        # - name: ConnectionStrings__Default
        #   value: "Host=eso-db-service;Port=5432;Database=esoDb;Username=postgres;Password=admin"
        resources:
          requests:
            cpu: "500m"
            memory: "512Mi"
          limits:
            cpu: "1"
            memory: "1Gi"