apiVersion: v1
kind: ServiceAccount
metadata:
  name: saga-gateway-sa
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: saga-gateway-jobmanager
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "delete"]
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "list", "create", "delete"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: saga-gateway-jobmanager-bind
subjects:
- kind: ServiceAccount
  name: saga-gateway-sa
roleRef:
  kind: Role
  name: saga-gateway-jobmanager
  apiGroup: rbac.authorization.k8s.io
